### ISSUE TITLE
Live video source 

### ISSUE THREAD

**Issue by sfahadshahzad** [FranceBB/VideoTek#2]
Hi,

Is there any way to get live video source from decklink sdi.

Regards,

Fahad

**Comment by FranceBB** [comment]
Well, I mean, in theory there's nothing stopping you from using a live video feed instead of a file.
When it comes to files you're using indexers like ffms2 and libav like:

```
FFMpegSource2("whatever.mxf", atrack=-1)

VideoTek()
```

or

```
video=LWLibavVideoSource("whatever.mxf")
audio=LWLibavAudioSource("whatever.mxf")
AudioDub(video, audio)

VideoTek()
```

Of course there are other indexers, the likes of DGIndex etc but anyway we're digressing.
On a live source, however, you need something else to pass it to the frameserver.
For instance, if you have an SDI feed in input you can connect the SDI cable to a Blackmagic Decklink card via PCI-Express in a workstation. At that point, all is left is to grab that and you can do it via DirectShowSource().
This is because, unlike the other indexers that "index" the file (it's literally in the name), DirectShowSource() uses the Windows API to call DirectShow and of course you should be able to use any DirectShow sources available / exposed by Windows.

For reference: http://avisynth.nl/index.php/DirectShowSource - https://trac.ffmpeg.org/wiki/DirectShow
By the way, I think this is more related to indexers rather than to VideoTek() in general so the best place to ask for this is on Doom9 in the Avisynth Usage section where I think others will be able to help you https://forum.doom9.org/forumdisplay.php?f=33 

Perhaps there's another way to do it, but my money is on DirectShow. Of course this would be limited to Windows only, so if you're on MacOS or Linux you're gonna be out of luck unfortunately. I know that Stephen (i.e qyot) has been doing lots of tests on Linux with Avisynth so perhaps he has some suggestions for doing it outside of Windows as well.

Nonetheless, I'm gonna close the issue 'cause I don't really think it belongs here, but please do open a topic on Doom9 and ask there, I'm sure they're gonna help you.

**Comment by FranceBB** [comment]
I'm back.
If you're on Windows, you might wanna check out this: https://forum.doom9.org/showthread.php?t=170311

That's VideoInputSource() a plugin replacement for DirectShowSource() when it comes to live video feeds.
You can use it as your indexer when you attach a capture card to it, then all you have to do is call VideoTek() afterwards to display the waveform and other things.
For instance:

```
VideoInputSource(0, "Composite", 1920, 1080, 25, 1)

VideoTek()
```

where:

device_id: is the n-th number of video capture device in your computer

connection_type: can be these string: "Composite","S_Video","Tuner","USB".

width, height: are the width and height of frames captured from video capture device.

fps_numerator, fps_denominator: are the FPS numerator and denominator.

num_frames: are how many frame will be captured from video capture device.

frame_skip: enable/disable frame skip while next new frame from video capture device is not ready.


Please try it out and report back to the Doom9 topic, not here, so that the author of the indexer, fieliapm, is gonna know. ;)
